# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec38bcd791332d866c213bce12de2805ac01702f3c74f092a03a5adf42f85228c11830864cf22d60891ee141b702081250a45ea2c2d58b519d952774da39b898

test:
  secret_key_base: cf4b4e33b259fa0736cbc6c647d2b9bdb8b33341be5ca3f99b466b434f89ab561923fa7d8bbd50b7e3c8a444bceb5bae56356018b26462734c341e014b770c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
